version: '3.9'

services:
  app:
    image: node-v16-sample
    container_name: node-sample
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - BUCKET_NAME=sample
      - AWS_ACCESS_KEY_ID=admin123
      - AWS_SECRET_ACCESS_KEY=admin123
      - S3_ENDPOINT=http://minio:9000
    tty: true
    ports:
      - '3000:3000'
    depends_on:
      - minio
  minio:
    image: quay.io/minio/minio:latest
    container_name: s3-minio
    environment:
      MINIO_ROOT_USER: admin123
      MINIO_ROOT_PASSWORD: admin123
    command: server --console-address ":9090" /data
    volumes:
      - ./minio/data:/data
    tty: true
    ports:
      - 9000:9000
      - 9090:9090
  mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set s3-minio http://minio:9000 admin123 admin123;
      /usr/bin/mc mb s3-minio/sample --region=ap-northeast-1;
      /usr/bin/mc policy set public s3-minio/sample;
      exit 0;
      "
